<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Demo</name>
   <tag></tag>
   <elementGuidId>44228983-82a2-4d60-8ebf-a1e1a4a664e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.nav-link.me-lg-3</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='navbarResponsive']/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ea1c0aa3-6863-4efb-8f15-5945358f6a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>nav-link me-lg-3</value>
      <webElementGuid>20b9e055-5819-459d-b19d-a2a86196c3f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://demo.firefly-iii.org/</value>
      <webElementGuid>28614bd7-ea4c-4d16-89db-fd2e0cae7236</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Demo</value>
      <webElementGuid>e78efd8b-7ac6-43d7-9351-790ac423e7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbarResponsive&quot;)/ul[@class=&quot;navbar-nav ms-auto me-4 my-3 my-lg-0&quot;]/li[@class=&quot;nav-item&quot;]/a[@class=&quot;nav-link me-lg-3&quot;]</value>
      <webElementGuid>8cc90dbf-30d9-4d8c-a64c-5e7c88f0b17b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navbarResponsive']/ul/li/a</value>
      <webElementGuid>cd23428f-fdc5-4b44-a6a0-1a7be07bf134</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Demo')]</value>
      <webElementGuid>a3cbd05e-8f62-41ec-a4d4-71b836e95c1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://demo.firefly-iii.org/')]</value>
      <webElementGuid>59d48380-7249-4c3c-8662-40bfb37db085</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>4c83de1d-878a-4743-9d68-2011ee43e40d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://demo.firefly-iii.org/' and (text() = 'Demo' or . = 'Demo')]</value>
      <webElementGuid>93d08ae1-93a7-4297-8931-b29ac1b1c3cc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
