<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>create new transaction - withdrawal</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>fa7d971e-7bd7-4a6d-9ad5-a217eb18fea6</testSuiteGuid>
   <testCaseLink>
      <guid>4fad701a-6d10-4349-8e29-f9098bffd234</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - withdrawal/TC1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5729f39c-0e64-43ee-a01c-46957bf0dcc8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f4992c68-0352-4956-ab24-3a7064328b69</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>452fbe3a-2a52-4668-8616-937e8cb940c8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - withdrawal/TC2_choice_recommendation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a329e801-0475-4332-858d-572f63fff4a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>470f5736-bb41-49e2-9065-06dc750b5aec</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>bac90705-6a69-4fcb-8e0c-d01189b0d235</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - withdrawal/TC2_only_input</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae6080ba-02ac-4a2d-ae15-3ce5bc4d8b29</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8340176d-ecdc-437a-9b1a-205bcdc9a457</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - withdrawal/TC3_choice_recommendation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64543dca-2f13-49e0-9ecb-2dddaad97c2b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5d0ee781-0d2d-45d8-9936-363dfb07993f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>df800841-3af7-4364-a37b-d9bb4f8e22da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - withdrawal/TC3_only_input</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85f9122c-1e45-4675-933f-575482670072</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f3d31435-9bc1-45c1-93d2-19924c7d763e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - withdrawal/TC4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f059277d-b3fd-4619-882a-0d2fdf38b70a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf70902c-1104-45e0-b226-9783f25803e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f489329a-8a04-4b49-abbe-2375c6b6a53a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - withdrawal/TC5</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>cc59d0cc-2a6a-47bb-bd2d-8eabd79267b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - withdrawal/TC6</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac980082-aaeb-4a45-bff0-f31c748da463</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34ab4eaa-e767-4191-bc6f-05a16dd16937</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39b8a14c-f50f-4e02-929f-85ff7fbf3872</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - withdrawal/TC7</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0e79fe64-c53c-4aed-acab-6e1ab985cb4a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6a36a13b-2571-4e26-994b-23e150e8867a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f754adf0-2803-4d4e-95be-64e95df2ad3b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2a2620da-ff28-42ba-9fb9-26929376303a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c5ca04f-48b6-4ad8-a607-79fb7fecf63a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>40d5374d-a466-42b8-8171-69f553e5bf33</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c4a00f67-94dc-4d03-bac0-a703c9fffb7c</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
