<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>create new transaction - transfer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>dcfe3f71-60c9-4b7d-96a8-4cb445edacda</testSuiteGuid>
   <testCaseLink>
      <guid>d1fe84e0-5c63-4f95-8adc-e854b6ed50fa</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - transfer/TC1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efa03398-71aa-4b57-ae7c-4c9b1bb5d92f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2e0a8d16-ae92-4839-b61a-d9b96eb73190</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>36316805-6a61-4edb-ba12-20b6795f02e6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - transfer/TC2_choice_recommendation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c47d521-f84b-4c68-a945-0dab888455e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>13ea7140-1c70-458b-a55c-2cb60fa39750</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16ce29cd-c374-4dda-b270-15a5a91fbfe0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - transfer/TC2_only_input</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef3e6cae-ecb3-4413-96e1-655eced179f7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>86f3b41f-461a-47bc-89c8-6922280237a5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - transfer/TC3_choice_recommendation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fc93fd71-15a0-45e4-bf3c-c1db3b9b6f14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c5b0b764-f4b9-4649-a0e8-35b55cc56294</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>599f0ef0-0d10-430c-8e07-7013d9f7434d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - transfer/TC3_only_input</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b3caacae-ed0f-4fb8-b39a-8e841189445a</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>57d7fdb9-702d-44bd-8b67-4d040a655679</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - transfer/TC4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>714894a7-828d-45c1-8f9e-9ea73f9e6ad0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c89f102-c23f-465b-9039-f2e715415897</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>cb38938f-aa80-492d-930d-b31c8fe8fa4f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - transfer/TC5</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>44b6d700-9d1a-4cbd-baca-87a8138627df</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - transfer/TC6</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>06c0636e-71ed-4b4d-95b5-438092695005</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>735580cc-642f-4356-af6d-77473ea3be9d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d5f812f5-205c-4ac9-93e1-65ce88b52ca8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/create new transaction - transfer/TC7</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9e98db80-cf3f-47f1-a765-19cd4870862e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a42f13f7-37b2-422d-b6cd-bdac909e2490</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1126dc7c-427f-4938-9d90-b3f76acbdd14</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92166847-9abf-47d3-a46c-612842387c96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>60b5b49f-6e2b-4c74-a3c6-9a4510389fa2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6cda962-4243-4d6d-9b72-cdf32579b232</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6361ca49-7a9d-4636-950f-a1de63acaa18</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
