<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>new asset account</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>cb63ad3a-d0fd-401d-9e6a-06ac43df0234</testSuiteGuid>
   <testCaseLink>
      <guid>03b7dc84-f1f5-4155-88b4-041edb6ba843</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/new asset account/TC1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b7ffb69a-305a-425e-85a6-941cff035af2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a79e79e7-ab7d-455a-964e-e01b0ade476c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>808326fd-3e0f-4da5-9a59-d924950c7875</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/new asset account/TC3_TC4_TC5_TC6_TC7</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>88ca6a96-7bba-49b4-bc09-2b2730d475d8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5458f139-24b2-4941-83ba-abfab8c4e15b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16ffd032-87cd-46fe-b36f-eed339dcc172</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c6e32e6d-9315-47ad-a0bf-c6b7e2889b69</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/new asset account/TC8</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ccb935ac-f16f-4e32-8f4e-ae63fcac098d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3c6a2c9-fe2e-43b3-a46b-52228bbb56ca</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b4af06c5-aa0e-40cc-a176-720326a804cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/new asset account/TC9</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c853e498-7074-4bfc-b857-19cbff79480a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e73e8282-ba60-4d7b-8fff-cbd455bba9ff</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d1df2871-5dfd-4551-9531-b94695a37317</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/new asset account/TC10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57e1237b-ecf4-4e28-a2ae-a3af350a8e5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5293874d-0992-4289-8bd0-aa9c73b08fb6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c0caac74-c03c-4112-844e-76c56ac29e7f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/new asset account/TC12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f2d64993-5286-4b82-a539-228628a995dd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b11dade-166b-462d-9893-b99ee03b1b89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c87d70a7-09fe-4738-aef0-78c9cc01a665</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>21e8dd58-62ac-48ac-9494-2575c5cbd744</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/new asset account/TC13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1296500b-03c6-47d0-9c7c-5b92381491a2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b80a7ec1-e3c8-483e-a332-c7697a9f991f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0b094bc6-cefe-4940-bd4a-05a4675fbe84</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63612afd-3900-4ef2-b893-ec1cceff7803</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c6acf43c-ed2b-44e8-bf79-725b1e23468e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e1d7459-337d-4c70-9630-28c3121a3f57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/new asset account/TC14_TC15_TC16_TC17_TC18</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>57dd854b-aec1-4631-83e6-c9bc888adbbc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>016f509f-1adb-467a-bb62-6f8398d39ffa</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6412547e-821d-429d-849d-71ef50ed86e3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/new asset account/TC19</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6cb63deb-97a5-46af-ab1f-bdb6c7dbcfe0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3ab228d-3eae-47e0-b91a-8c0b29ebc5cc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>daf090f7-29ff-4e30-b704-4490030c67a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8e6fcefe-6f6e-4ac5-b627-6c41191d82bb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/new asset account/TC20</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>9705d287-965b-4009-af30-7aac3812d0cc</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/new asset account/TC21</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcbc6684-58b0-4e7b-9291-ba8c5a2bedf8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0ff739b0-f485-45c3-998f-c5f49862eab3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>eace1ce1-4edb-4017-9229-2c28d504d35e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1a9e579a-a92b-4d4b-8e15-e9fd537aedcf</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/new asset account/TC22</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>8d895823-5245-4662-beed-49261fee464a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/GUI/new asset account/TC23</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
