<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>create new transaction-transfer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>18199400-4d1d-44bc-8110-e1bda7e2bd17</testSuiteGuid>
   <testCaseLink>
      <guid>ada0b515-0bbb-4b6a-bfce-32e28642b8c7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-transfer/TC1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd08df0b-1154-438b-a027-60ce539e5fa5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>390ac2f8-f0f3-403a-bfb0-920830aa7691</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4eee5099-ca75-4e4d-97e1-e8ccb852341a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-transfer/TC2_TC3_TC4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>84a9a37b-c387-4055-83d3-2543baa1edd8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf4ebf35-9711-4963-8608-bc2680aaf097</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7905a345-1086-4f49-b83c-b0fc8ede00b1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-transfer/TC6_TC7_TC11_TC13_TC14_TC17</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>207083e9-1e9d-44f5-999d-5bb7bef37185</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ac3e9cfa-a125-43a5-bb6f-9f1b11381878</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1aa19241-baf9-48bc-8bec-395dfa8080ea</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>539c0a3b-7bf8-4660-af7e-3f948be44423</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>974e718b-6a07-4499-b0e7-33d61606391b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e62cf743-d5d4-49ad-9e6c-ba622a7aa7bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0fde9c60-99f8-4751-9fa7-e2a182ed36e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-transfer/TC8_TC9_TC10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d65f4310-0d74-4740-9e21-9c669abc7f43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>34701dd0-07ec-4e37-bb35-0f74844fad07</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e1f3c0dd-b2d5-405b-91c7-c455de6b9735</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-transfer/TC15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bf9d4036-91b4-4942-9060-1d3fa4d6d4fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8600a39e-fcbf-47b5-88b8-8b9d34b57378</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1928131-70c1-4af3-8282-d11b2e5929c1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86221ba2-0426-401c-a5b2-b6d8f1095a01</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9a1c5b5c-5188-4b9b-b77e-337d4775931e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>75c91d6c-2360-4bc3-9ff2-c2ab888a038e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5c211c8e-7b0e-49c0-adf7-0923046e45b0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>aa601796-0da7-4c7e-9bd6-85e6d9f62c1a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-transfer/TC18</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e1480618-bf0a-4104-95e8-26ab6e0495b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-transfer/TC19</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
