<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>create new transaction-withdrawals</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>584ba9e9-3458-4fcf-ab90-5d70d647c8a5</testSuiteGuid>
   <testCaseLink>
      <guid>d35c9b52-d6bf-4cd7-aa6c-29709a5c3d17</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-withdrawals/TC1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>64e37d37-9864-4486-98e5-ff4c5725bdf2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d81a09b5-67c4-4c5f-a961-19bf7a8b88a4</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>33425190-fa78-4260-ba61-257316fac6c3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-withdrawals/TC2_TC3_TC4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>68fe4d72-1b88-4cea-bab4-52458c3993c9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cd5ebf82-0e24-4fc6-854e-1960b7992df0</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>468c0038-b382-45bf-8420-e9c7dde055e0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-withdrawals/TC6_TC7_TC12_TC13_TC16_TC18</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8fb6d1f9-a6db-4e05-8db2-69217f76516d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4c8951e-a8eb-427b-a252-67685bf5b317</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3a5d4f99-d4c8-4838-971a-75c5d5410292</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12a4c870-84e7-43e2-a66b-6a6397349139</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c316a237-3c97-493a-9594-8cf430e92e43</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>03170bb4-7d2d-4dde-8c58-4015e4290b7e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>8608da57-be10-41d3-8b6a-0407076a20c2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-withdrawals/TC8_TC9_TC10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>00fcaa52-48a3-4da8-86a4-e44951a405ad</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe832a0b-e74d-421a-b2bd-a804e7df513f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>9b92152b-a3ed-44d5-b7c1-5856bfc510f5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-withdrawals/TC15</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>09a20d62-7598-43b5-8d48-bb5c8a3f589e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8790587-7199-41fe-8840-8a3abedd720d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>269d6464-80fd-47aa-ac6a-9fcd2bf42f92</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>49074319-479b-41a9-a820-2909ce5b2d8f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66bdb321-236b-4bde-a58f-fd82f1d19794</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8d7512ce-cf34-4680-8ccc-32a90fc251a7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>699e8222-f7a9-4380-9ece-fdee47d37003</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0af83337-cece-428a-a8ca-2e28b15c7034</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-withdrawals/TC17</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>e454b2b8-f941-42d4-bf5a-dced9d85c460</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/create new transaction-withdrawals/TC19</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
