<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>new expense account</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>406e76ef-2e63-4562-b1a2-1dda99cf107b</testSuiteGuid>
   <testCaseLink>
      <guid>0789a00e-0aa5-470b-bdb0-05d4b55eb69b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/new expense account/TC1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>05fc5aa9-adbf-438e-b82a-a9fdfe6f5be3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fcb81f3-1e25-4d05-a181-1ad208f391d6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f9aaa9dd-4b81-4fe5-82de-5de5eee0c2a3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/new expense account/TC2_TC3_TC4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>326c6503-93a6-48a9-bdf4-3effca7c2b7d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>aadd37ae-c534-4e24-a7f5-c9b2733a6567</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>49195546-3e2c-4835-865a-335f9fd2b68e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/new expense account/TC5_TC6_TC7_TC7_TC8_TC9_TC10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>97856b9c-3848-4836-834e-8d693d86ea05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e10728ca-fdd1-4644-8ad2-0e1c8d474ecd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3329f8ec-78ec-41c2-b51e-440c44145a61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ae1c8f92-805c-4362-8069-c50a668ceaca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>69ad8b9a-11dc-4ace-93c9-0079afd585b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a234473a-ca7e-4c50-8688-49224c0d7193</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3e3d59de-86b7-4f98-adf5-f0e9c3f74720</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/new expense account/TC11_TC12</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a14e2dae-d8c3-40b1-b8eb-97d1f02b1a2e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9b1e08f5-d852-4a76-a6e1-d295c4a29fee</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f5118f4-d46d-4368-b1ec-54ac1e899a2a</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
