<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>new asset account</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>c50e4c1f-472b-4d0c-8890-9b37fdcae939</testSuiteGuid>
   <testCaseLink>
      <guid>0be3372b-493a-4eb6-9fa9-622c39ce561f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/new asset account/TC1</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2943e942-0fee-477a-bff6-c3649d0c4455</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c3464b53-87c6-4b5f-a353-e660831fbb39</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16855fa4-e97c-4776-9739-0958f9c823da</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/new asset account/TC2_TC3_TC4</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>12ceceec-8829-4dc3-ba34-e7c5d22cf83f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3ef1afb5-d78d-4447-a997-254740dcc872</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f6d53f8c-d2e7-40bc-8927-3b108908108a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/new asset account/TC5</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c1f07fe6-22cf-439c-a43a-57e4cb6ae166</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9c0a326f-9849-4201-94c5-2bab488062ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>838f35a6-5c49-4573-a796-5ec3093de426</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>3765a6ec-5505-4596-8471-42f4c5d92152</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/new asset account/TC6_TC7_TC8_TC9_TC10</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d569036-9901-4fee-9f2f-da344e261ade</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ca180fba-e074-4f11-b5d5-1ebb4b39c528</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd73690f-446f-47a3-98d8-63e445747691</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c10bbed5-0aff-4e81-86a2-cbe9274d73e8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a6193a5c-ef6d-4a77-81cd-b2363eaea1cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>5b06418e-371f-47f3-8f17-222a0788dd75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Functional/new asset account/TC11_TC12_TC13</testCaseId>
      <usingDataBindingAtTestSuiteLevel>false</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>45df17ea-7fac-4244-b5b3-3f9b9d37e43a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6ef1fdc4-034c-4b11-89ea-0ad0b168e894</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e7ac0a81-6e70-4b4a-bd61-d8910182970e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffea4bf6-1550-40a0-b4fb-b6d1024cc141</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
