<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_The transaction amount field is required</name>
   <tag></tag>
   <elementGuidId>02862c0a-dff3-4446-8e90-54f6011016ae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.text-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='amount-info']/div/ul/li</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>4ec2b45f-5e50-4a40-8984-0d0c86f01f32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>a6fc6914-61c7-436d-a91c-6771077db046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>The transaction amount field is required.</value>
      <webElementGuid>8eb691af-8bbe-411b-9d8e-a013561ab5c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount-info&quot;)/div[@class=&quot;form-group has-error&quot;]/ul[@class=&quot;list-unstyled&quot;]/li[@class=&quot;text-danger&quot;]</value>
      <webElementGuid>5823bf3b-7100-407f-b612-3f5e1beddba3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='amount-info']/div/ul/li</value>
      <webElementGuid>4ffdaae4-a104-45be-ac3a-4ff846d6417e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/ul/li</value>
      <webElementGuid>b4e35af2-6881-48bc-9941-e32fbfaa86fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[(text() = 'The transaction amount field is required.' or . = 'The transaction amount field is required.')]</value>
      <webElementGuid>b1005b60-19cb-4471-ac4b-4db8e475880a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
