<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Euro ()</name>
   <tag></tag>
   <elementGuidId>80086cdc-c2f3-4aea-9e60-a921272688d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_currency_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_currency_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>58cc235a-330d-41eb-9181-d18c820dd6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b2f55d7a-29dd-4696-817e-93bdc2695086</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currency_id</value>
      <webElementGuid>9adff665-87cf-4ae4-b5ff-07e68a569abb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_currency_id</value>
      <webElementGuid>7daef5ef-4fc3-413b-86a7-e95198fce458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b75ff606-ee0c-42d1-ad9b-a9cdcbc7666c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>af7ad6a4-c2a1-4101-93fb-5ef2bc708deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Euro (€)British Pound (£)Hungarian forint (Ft)US Dollar ($)</value>
      <webElementGuid>d3a8f6b0-8f34-4bcc-8247-222838de6731</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_currency_id&quot;)</value>
      <webElementGuid>f5a4ca09-b811-4625-8519-a3025272b587</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_currency_id']</value>
      <webElementGuid>e3a9ffd1-c6e6-4b37-8be3-270914679a59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='currency_id_holder']/div/select</value>
      <webElementGuid>dfa588cd-ea4e-42e7-8bc3-5557d03c4614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>0421881c-d2ed-4e2d-a5cc-0fb1fb05abcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'currency_id' and @id = 'ffInput_currency_id' and (text() = 'Euro (€)British Pound (£)Hungarian forint (Ft)US Dollar ($)' or . = 'Euro (€)British Pound (£)Hungarian forint (Ft)US Dollar ($)')]</value>
      <webElementGuid>b165ee9f-4ccf-4e2a-815a-eebc7ef66056</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
