<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Opening balance date_col-sm-8</name>
   <tag></tag>
   <elementGuidId>1d37a7e1-9118-4c1f-a5af-52db1ff377b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#opening_balance_date_holder > div.col-sm-8</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;ffInput_opening_balance_date&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a7887660-4cac-436f-b1e5-ea3604f219d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-sm-8</value>
      <webElementGuid>361be1ff-b260-4561-bc47-9eae550fa17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opening_balance_date_holder&quot;)/div[@class=&quot;col-sm-8&quot;]</value>
      <webElementGuid>c0371fa5-e64e-4e23-b29f-11811e9582ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opening_balance_date_holder']/div</value>
      <webElementGuid>ec73a30e-7faa-4d18-a3a9-1c909ec17535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div</value>
      <webElementGuid>b4ddd9f0-5de7-4849-b0bb-8becbdd07b5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
