<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_This is not a valid IBAN</name>
   <tag></tag>
   <elementGuidId>f3bd9601-165c-4dbc-85a0-39b7d2cea625</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#iban_holder > div.col-sm-8 > p.text-danger</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='iban_holder']/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>ad8c35ac-d809-474f-9fbc-64436255375f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-danger</value>
      <webElementGuid>f930e508-f5a8-45c5-a83f-29c03795f627</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is not a valid IBAN.</value>
      <webElementGuid>c248c720-25d3-4f34-8b24-1db45e46c73a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;iban_holder&quot;)/div[@class=&quot;col-sm-8&quot;]/p[@class=&quot;text-danger&quot;]</value>
      <webElementGuid>4c3c1f86-275b-4da5-9edc-7fb31b9f8394</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='iban_holder']/div/p</value>
      <webElementGuid>bc1a0f80-9882-404a-b7d2-5527bf953760</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/p</value>
      <webElementGuid>2270a4e5-1cf1-4d42-b998-010fc5dfc608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'This is not a valid IBAN.' or . = 'This is not a valid IBAN.')]</value>
      <webElementGuid>db436a3a-8311-44b1-8290-3d5d1ff0e9a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
