<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Submit</name>
   <tag></tag>
   <elementGuidId>81a088a0-e839-4689-bfdf-68bfdca5a8d8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submitButton</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submitButton']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>45aa1e7a-6d18-4af0-a946-48b80de36380</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>submitButton</value>
      <webElementGuid>5543f4d3-9760-40dd-862f-dca5219c9938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>71e656c2-e7cc-4851-a2e8-2fde7ca4dadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit
                        </value>
      <webElementGuid>90d3348a-7d9c-44d4-b025-6c25d83cec32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submitButton&quot;)</value>
      <webElementGuid>0e991b9b-12bc-4a03-a9c4-c9ef2a8fc802</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='submitButton']</value>
      <webElementGuid>c1a26c41-ab5c-441e-b88f-8e3662bcf90f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/section[2]/form/div[2]/div/div/div[3]/div/button</value>
      <webElementGuid>cc6f6613-6f35-4082-9b55-6e2e95e3f19e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>5ccb6c30-7882-4bb3-8cf7-cbf3baf749ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'submitButton' and (text() = 'Submit
                        ' or . = 'Submit
                        ')]</value>
      <webElementGuid>4409adb2-0a13-41c4-b59c-c261a39a30ed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
