<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dropdown_currency</name>
   <tag></tag>
   <elementGuidId>240426fc-3041-4e1c-ba92-d9a0710a08f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ffInput_currency_id</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ffInput_currency_id']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b82fe4d3-7362-42bf-83c4-d622a485e1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0c1a2077-535a-476c-baf6-ece8a42bfce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>currency_id</value>
      <webElementGuid>9e355637-6eff-4a80-a078-ed58f800c66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ffInput_currency_id</value>
      <webElementGuid>1d4af625-419f-4e9a-b4ef-4d6f3a125190</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7c02f220-a8b4-477e-ba8b-e8302e8d1f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>spellcheck</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d6484ec0-0bd3-4777-8fac-3ebe5bd039da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Euro (€)British Pound (£)Hungarian forint (Ft)US Dollar ($)</value>
      <webElementGuid>02446a4c-a704-4c65-b32d-aec143d107ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ffInput_currency_id&quot;)</value>
      <webElementGuid>af1b1c48-a2b2-48ca-b6bc-c632b1b0dff9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ffInput_currency_id']</value>
      <webElementGuid>0a4fdb43-9eac-4da2-abf6-efcfd24ed5e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='currency_id_holder']/div/select</value>
      <webElementGuid>a15e03e3-d295-45b9-a06c-87b51b1639a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6f0e3646-78da-4683-92cd-c4e81d2eded5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'currency_id' and @id = 'ffInput_currency_id' and (text() = 'Euro (€)British Pound (£)Hungarian forint (Ft)US Dollar ($)' or . = 'Euro (€)British Pound (£)Hungarian forint (Ft)US Dollar ($)')]</value>
      <webElementGuid>b44b37bd-e920-4161-96ee-2ea8dbe08226</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
